version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: eduverse-postgres
    restart: always
    environment:
      POSTGRES_DB: eduverse_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "11111111"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eduverse-network

  redis-cache:
    image: redis:7-alpine
    container_name: eduverse-redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - eduverse-network

  minio-storage:
    image: minio/minio:latest
    container_name: eduverse-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: eduverse_admin
      MINIO_ROOT_PASSWORD: eduverse_password
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - eduverse-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  eduverse-network:
    driver: bridge