spring:
  application:
    name: EduVerse

  datasource:
    url: jdbc:postgresql://localhost:5432/eduverse_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:11111111}
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: EduVerse-Hikari-Pool
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      format_sql: true
      highlight_sql: true
      jdbc:
        batch_size: 20
        order_inserts: true
        order_updates: true

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 25MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  mail:
    host: ${MAIL_HOST:smtp-relay.brevo.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:ab4f2e001@smtp-brevo.com}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      # password: ${SPRING_REDIS_PASSWORD}
      connect-timeout: 5000ms
      timeout: 5000ms

      ssl:
        enabled: false
server:
  port: 8088

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

aws:
  s3:
    endpoint: http://localhost:9000
    region: us-east-1
    access-key: eduverse_admin
    secret-key: eduverse_password
    bucket-name: eduverse-bucket