spring:
  application:
    name: EduVerse

  datasource:
    url: jdbc:postgresql://localhost:5432/eduverse_db
    username: postgres
    password: "11111111"
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: EduVerse-Hikari-Pool
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      format_sql: true
      highlight_sql: true
      jdbc:
        batch_size: 20
        order_inserts: true
        order_updates: true

  jwt:
    secret: "8d7c4f1e9b2a6c5f7e8d3a1b9c6d4e2f5a7b8c9d1e3f4a6b7c8d9e1f2a3b4c5d"
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 25MB
server:
  port: 8088

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

