CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE auth_provider AS ENUM ('LOCAL', 'GOOGLE');
CREATE TYPE user_role AS ENUM ('USER', 'CREATOR', 'ADMIN');
CREATE TYPE user_status AS ENUM ('ACTIVE', 'BANNED', 'DELETED');
CREATE TYPE rank_level AS ENUM ('BRONZE', 'SILVER', 'GOLD', 'DIAMOND');

CREATE TYPE wallet_tx_type AS ENUM (
    'DEPOSIT',
    'WITHDRAW',
    'BUY_DOCUMENT',
    'SELL_DOCUMENT',
    'DOWNLOAD_REWARD',
    'REFUND'
);

CREATE TYPE tx_direction AS ENUM ('IN', 'OUT');
CREATE TYPE tx_status AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED');

CREATE TYPE document_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'HIDDEN');
CREATE TYPE document_price_type AS ENUM ('FREE', 'COIN', 'VND');

CREATE TYPE payment_provider AS ENUM ('PAYOS', 'VNPAY', 'MOMO');
CREATE TYPE payment_status AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED');

CREATE TYPE friend_status AS ENUM ('PENDING', 'ACCEPTED', 'BLOCKED');
CREATE TYPE conv_type AS ENUM ('PRIVATE', 'GROUP');
CREATE TYPE msg_type AS ENUM ('TEXT', 'IMAGE', 'FILE', 'SYSTEM');
CREATE TYPE member_role AS ENUM ('OWNER', 'ADMIN', 'MEMBER');

CREATE TYPE report_status AS ENUM ('PENDING', 'RESOLVED', 'REJECTED');
CREATE TYPE withdrawal_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'PAID');

-- Cấu hình hệ thống
CREATE TABLE system_configs (
                                config_key VARCHAR(50) PRIMARY KEY,
                                config_value TEXT NOT NULL,
                                description TEXT,
                                updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO system_configs (config_key, config_value, description) VALUES
                                                                       ('COIN_EXCHANGE_RATE', '1000', 'Tỷ giá: 1000 VND = 1 EduCoin'),
                                                                       ('PLATFORM_FEE_PERCENT', '10', 'Phí hoa hồng sàn thu người bán: 10%'),
                                                                       ('DOWNLOAD_REWARD_COIN', '1', 'Số xu người đăng nhận được khi có 1 lượt tải free: 1 EduCoin');

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       email VARCHAR(100) NOT NULL UNIQUE,
                       password_hash VARCHAR(255),
                       full_name VARCHAR(100),
                       avatar_url TEXT,
                       provider auth_provider DEFAULT 'LOCAL' NOT NULL,
                       role user_role DEFAULT 'USER' NOT NULL,
                       rank_level rank_level DEFAULT 'BRONZE' NOT NULL,
                       contribution_point INT DEFAULT 0 NOT NULL,
                       status user_status DEFAULT 'ACTIVE' NOT NULL,
                       created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT check_contribution_point CHECK (contribution_point >= 0)
);

CREATE TABLE wallets (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
                         vnd_balance DECIMAL(15,2) DEFAULT 0 NOT NULL,
                         coin_balance INT DEFAULT 0 NOT NULL,
                         version INT DEFAULT 0 NOT NULL, -- Định danh phiên phục vụ Optimistic Locking trong Spring Boot
                         created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT check_wallet_balance CHECK (
                             vnd_balance >= 0 AND coin_balance >= 0
                             )
);

CREATE TABLE wallet_transactions (
                                     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                     wallet_id BIGINT NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,
                                     type wallet_tx_type NOT NULL,
                                     direction tx_direction NOT NULL,
                                     amount_vnd DECIMAL(15,2) DEFAULT 0 NOT NULL,
                                     amount_coin INT DEFAULT 0 NOT NULL,
                                     balance_vnd_after DECIMAL(15,2), -- Sao lưu số dư để đối soát (Audit Log)
                                     balance_coin_after INT,
                                     reference_type VARCHAR(50),      -- Ví dụ: 'DOCUMENT_ORDERS', 'PAYMENTS'
                                     reference_id VARCHAR(100),       -- ID của bản ghi liên quan
                                     idempotency_key VARCHAR(100) UNIQUE, -- Chống xử lý trùng lặp giao dịch
                                     status tx_status DEFAULT 'SUCCESS' NOT NULL,
                                     description TEXT,
                                     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                                     CONSTRAINT check_tx_amount CHECK (
                                         amount_vnd >= 0 AND amount_coin >= 0
                                         )
);

CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(100) NOT NULL,
                            type VARCHAR(50), -- Định danh cấp bậc (ví dụ: TRUONG_DAI_HOC, MON_HOC)
                            parent_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
                            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE documents (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           title VARCHAR(255) NOT NULL,
                           description TEXT,
                           file_url TEXT NOT NULL,       -- Link tải file gốc trên S3/MinIO
                           preview_url TEXT,            -- Link file băm xem trước (3 trang đầu)
                           file_size BIGINT,
                           file_type VARCHAR(50) DEFAULT 'PDF',
                           price_type document_price_type DEFAULT 'FREE' NOT NULL,
                           price_coin INT DEFAULT 0 NOT NULL,
                           price_vnd DECIMAL(15,2) DEFAULT 0 NOT NULL,
                           download_count INT DEFAULT 0 NOT NULL,
                           view_count INT DEFAULT 0 NOT NULL,
                           uploader_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                           category_id BIGINT NOT NULL REFERENCES categories(id),
                           status document_status DEFAULT 'PENDING' NOT NULL,
                           reject_reason TEXT,
                           created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT check_document_price CHECK (
                               (price_type = 'FREE' AND price_coin = 0 AND price_vnd = 0) OR
                               (price_type = 'COIN' AND price_coin > 0 AND price_vnd = 0) OR
                               (price_type = 'VND' AND price_vnd > 0 AND price_coin = 0)
                               ),
                           CONSTRAINT check_document_counter CHECK (
                               download_count >= 0 AND view_count >= 0
                               )
);

CREATE TABLE document_downloads (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
                                    downloaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                    reward_counted BOOLEAN DEFAULT FALSE NOT NULL -- Đánh dấu đã cộng xu cho tác giả chưa (chống spam)
);

CREATE TABLE document_orders (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 buyer_id BIGINT NOT NULL REFERENCES users(id),
                                 seller_id BIGINT NOT NULL REFERENCES users(id),
                                 document_id BIGINT NOT NULL REFERENCES documents(id),
                                 price_vnd DECIMAL(15,2) DEFAULT 0 NOT NULL,
                                 price_coin INT DEFAULT 0 NOT NULL,
                                 platform_fee_vnd DECIMAL(15,2) DEFAULT 0 NOT NULL,
                                 platform_fee_coin INT DEFAULT 0 NOT NULL,
                                 status tx_status DEFAULT 'SUCCESS' NOT NULL,
                                 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                                 CONSTRAINT check_not_buy_own_document CHECK (buyer_id <> seller_id)
);

CREATE TABLE document_reports (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
                                  reporter_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                  reason TEXT NOT NULL,
                                  status report_status DEFAULT 'PENDING' NOT NULL,
                                  admin_note TEXT,
                                  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                  resolved_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE payments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                          order_code VARCHAR(100) NOT NULL UNIQUE, -- Mã đơn chuyển sang PayOS/VNPAY
                          amount_vnd DECIMAL(15,2) NOT NULL,
                          coin_amount INT NOT NULL,
                          provider payment_provider NOT NULL,
                          checkout_url TEXT,
                          qr_code_url TEXT,
                          status payment_status DEFAULT 'PENDING' NOT NULL,
                          raw_webhook JSONB, -- Lưu log thô từ ngân hàng bắn về để đối soát khi lỗi
                          created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                          paid_at TIMESTAMP WITH TIME ZONE,

                          CONSTRAINT check_payment_amount CHECK (
                              amount_vnd > 0 AND coin_amount > 0
                              )
);

CREATE TABLE withdrawal_requests (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                     amount_vnd DECIMAL(15,2) NOT NULL,
                                     bank_name VARCHAR(100) NOT NULL,
                                     bank_account_no VARCHAR(50) NOT NULL,
                                     bank_account_name VARCHAR(100) NOT NULL,
                                     status withdrawal_status DEFAULT 'PENDING' NOT NULL,
                                     admin_note TEXT,
                                     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                     processed_at TIMESTAMP WITH TIME ZONE,

                                     CONSTRAINT check_withdraw_amount CHECK (amount_vnd > 0)
);

CREATE TABLE friendships (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                             receiver_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                             status friend_status DEFAULT 'PENDING' NOT NULL,
                             created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                             CONSTRAINT check_not_self_friendship CHECK (sender_id <> receiver_id),
                             CONSTRAINT uq_friendship_sender_receiver UNIQUE (sender_id, receiver_id)
);

CREATE TABLE conversations (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               type conv_type NOT NULL,
                               name VARCHAR(100), -- Chỉ dùng cho Group Chat
                               private_key VARCHAR(100) UNIQUE, -- Khóa tạo từ cặp ID (UserA_UserB) dùng định danh Chat 1-1 nhanh
                               created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
                               last_message_id BIGINT,
                               last_message_at TIMESTAMP WITH TIME ZONE,
                               avatar_url TEXT,
                               created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT check_private_conversation CHECK (
                                   (type = 'PRIVATE' AND name IS NULL AND avatar_url IS NULL AND private_key IS NOT NULL) OR
                                   (type = 'GROUP')
                                   )
);

CREATE TABLE messages (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
                          sender_id BIGINT NOT NULL REFERENCES users(id),
                          content TEXT,
                          type msg_type DEFAULT 'TEXT' NOT NULL,
                          reply_to_message_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,
                          file_url TEXT,
                          file_name VARCHAR(255),
                          file_size BIGINT,
                          created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                          is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
                          is_edited BOOLEAN DEFAULT FALSE NOT NULL,
                          deleted_at TIMESTAMP WITH TIME ZONE,
                          deleted_by BIGINT REFERENCES users(id),

                          CONSTRAINT check_message_content CHECK (
                              is_deleted = TRUE OR content IS NOT NULL OR file_url IS NOT NULL
                              )
);

ALTER TABLE conversations
    ADD CONSTRAINT fk_last_message
        FOREIGN KEY (last_message_id) REFERENCES messages(id) ON DELETE SET NULL;

CREATE TABLE conversation_members (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
                                      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                      nickname VARCHAR(50),
                                      role member_role DEFAULT 'MEMBER' NOT NULL,
                                      last_seen_message_id BIGINT REFERENCES messages(id) ON DELETE SET NULL, -- Đánh dấu trạng thái đã đọc
                                      joined_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                                      UNIQUE (conversation_id, user_id)
);

CREATE TABLE message_reactions (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
                                   user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                   emoji VARCHAR(20) NOT NULL,
                                   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                                   UNIQUE (message_id, user_id, emoji)
);

CREATE TABLE notifications (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                               title VARCHAR(255) NOT NULL,
                               content TEXT,
                               type VARCHAR(50),
                               reference_type VARCHAR(50),
                               reference_id VARCHAR(100),
                               is_read BOOLEAN DEFAULT FALSE NOT NULL,
                               created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_wallet_transactions_wallet_id ON wallet_transactions(wallet_id);
CREATE INDEX idx_wallet_transactions_created_at ON wallet_transactions(created_at DESC);
CREATE INDEX idx_categories_parent_id ON categories(parent_id);
CREATE INDEX idx_documents_uploader_id ON documents(uploader_id);
CREATE INDEX idx_documents_category_id ON documents(category_id);
CREATE INDEX idx_documents_status ON documents(status);
CREATE INDEX idx_documents_created_at ON documents(created_at DESC);
CREATE INDEX idx_document_downloads_user_doc ON document_downloads(user_id, document_id);
CREATE INDEX idx_document_orders_buyer ON document_orders(buyer_id);
CREATE INDEX idx_document_orders_seller ON document_orders(seller_id);
CREATE INDEX idx_document_reports_document_id ON document_reports(document_id);
CREATE INDEX idx_payments_user_id ON payments(user_id);
CREATE INDEX idx_payments_order_code ON payments(order_code);
CREATE INDEX idx_withdrawal_requests_user_id ON withdrawal_requests(user_id);
CREATE INDEX idx_friendships_sender_id ON friendships(sender_id);
CREATE INDEX idx_friendships_receiver_id ON friendships(receiver_id);
CREATE INDEX idx_conversation_members_user_id ON conversation_members(user_id);
CREATE INDEX idx_messages_conversation_created_at ON messages(conversation_id, created_at DESC);
CREATE INDEX idx_conversations_last_message_at ON conversations(last_message_at DESC);
CREATE INDEX idx_notifications_user_read ON notifications(user_id, is_read);